services:
  - type: web
    name: my-service
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t my-image .
    dockerCommand: |
      docker run -it --rm --name my-container my-image
      sleep 10  # Give it some time to start
      docker logs -f my-container
    envVars:
      - key: SERVER_PORT
        value: "8080"  # Ensure this matches the exposed port
    autoDeploy: true
